var_choice = IntVar()
Radiobutton(frame_list, text="Kopalnie", variable=var_choice, value=1, command=lambda: update_list(mines)).grid(row=0, column=0)
Radiobutton(frame_list, text="Pracownicy", variable=var_choice, value=2, command=lambda: update_list(employees)).grid(row=0, column=1)
Radiobutton(frame_list, text="Klienci", variable=var_choice, value=3, command=lambda: update_list(clients)).grid(row=0, column=2)

listbox = Listbox(frame_list, width=60, height=15)
listbox.grid(row=1, column=0, columnspan=3)
Button(frame_list, text="Pokaż", command=show_details).grid(row=2, column=0)
Button(frame_list, text="Usuń", command=remove_entity).grid(row=2, column=1)
Button(frame_list, text="Edytuj", command=edit_entity).grid(row=2, column=2)

Label(frame_form, text="Nazwa:").grid(row=0, column=0)
Label(frame_form, text="Lokalizacja:").grid(row=1, column=0)
Label(frame_form, text="Opis:").grid(row=2, column=0)

entry_name = Entry(frame_form)
entry_name.grid(row=0, column=1)
entry_location = Entry(frame_form)
entry_location.grid(row=1, column=1)
entry_desc = Entry(frame_form)
entry_desc.grid(row=2, column=1)

button_add = Button(frame_form, text="Dodaj", command=add_entity)
button_add.grid(row=3, column=0, columnspan=2)

Label(frame_details, text="Nazwa:").grid(row=0, column=0)
label_name_val = Label(frame_details, text="...")
label_name_val.grid(row=0, column=1)
Label(frame_details, text="Lokalizacja:").grid(row=0, column=2)
label_location_val = Label(frame_details, text="...")
label_location_val.grid(row=0, column=3)
Label(frame_details, text="Opis:").grid(row=0, column=4)
label_desc_val = Label(frame_details, text="...")
label_desc_val.grid(row=0, column=5)

map_widget = tkintermapview.TkinterMapView(frame_map, width=1200, height=500, corner_radius=5)
map_widget.set_position(52.23, 21.0)
map_widget.set_zoom(6)
map_widget.grid(row=0, column=0, columnspan=2)

root.mainloop()